---
abstract: 'Check socket functionality.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  Config: 0
  ExtUtils::MakeMaker: 6.59
  Socket: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Check-Socket
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Config: 0
  Exporter: 0
  Readonly: 0
  Socket: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Check-Socket/issues
  homepage: https://github.com/michal-josef-spacek/Check-Socket
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Check-Socket
version: '0.04'
